
POST http://localhost:3000/app/user/register
Content-Type: application/json

{
  "name": "Dev Ed",
  "email": "dev1@163.com",
  "password": "123456"
}


###

POST http://localhost:3000/app/user/login
Content-Type: application/json

{
  "email": "dev1@163.com",
  "password": "123456"
}


###

GET http://localhost:3000/app/posts
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWIyMjA4ZDY5YzU0OTFhYjRmNzMzZTAiLCJpYXQiOjE2MzkwNjM3NzJ9.io7a_si45k_OMllsdMLqCETXT_TTSR__gY3wvsNcTGU

###

GET http://localhost:3000/app/posts
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTlhNGYzZDBjOGZkMGE1ZDMzOGNjMzYiLCJpYXQiOjE2Mzc1MDU0OTZ9.ToilzDvLUh6Qd1FUqzQRpSZHenmcmUgmAJcAI_w8rZc